name: Build and Release Plugin

on:
  push:
    paths:
      - "bin/**"
      - "!.github/workflows/**"
      - ".github/workflows/main.yml"
env:
  ASDF_VERSION: v0.8.1
  ARBITARY_ISTIO_VERSION: 1.8.6
jobs:
  buildAndReleasePlugin:
    name: "Build and Release Plugin"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Get Latest Istio Release"
        id: istio-latest-version
        uses: actions/github-script@v4.0.1
        with:
          result-encoding: string
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            return github.repos.getLatestRelease({
              repo: 'istio',
              owner: 'istio'
            })
            .then(result => { return result.data.tag_name } )
            .catch(err => console.log(err))
      - name: "Latest Version Check"
        id: asdf-plugin-latest-test
        run: |
          sudo apt install curl git
          git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch "${ASDF_VERSION}"
          . $HOME/.asdf/asdf.sh
          INSTALLED_VERSION='unknown' 
          nohup asdf plugin test istio . 'istioctl version --short --remote=false' 2> /dev/null &
          sleep_seconds=10
          while true; do
            if [ $sleep_seconds > 300 ] && [ $INSTALLED_VERSION != "unknown" ] ; then
              break
            fi
            sleep $sleep_seconds
            while read line; do
              INSTALLED_VERSION=$line
            done < <(cat nohup.out)
            ((sleep_seconds=sleep_seconds+10))
          done
          echo "Latest Istio Version ... ${ISTIO_LATEST_VERSION}"
          echo "Installed Istio ... ${INSTALLED_VERSION}"
          [[ "${ISTIO_LATEST_VERSION}" == "${INSTALLED_VERSION}" ]] && installed="OK" || installed="KO"
          echo "::set-output name=installed::$installed"
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }} # automatically provided
          ISTIO_LATEST_VERSION: ${{ steps.istio-latest-version.outputs.result }}
      - name: "Pinned Version Check::1.8.6"
        id: asdf-istio-plugin-pinned-test
        run: |
          . $HOME/.asdf/asdf.sh
          INSTALLED_VERSION='unknown' 
          nohup asdf plugin test istio . --asdf-tool-version '1.8.6' 'istioctl version --short --remote=false' 2> /dev/null &
          sleep_seconds=10
          while true; do
            if [ $sleep_seconds > 300 ] && [ $INSTALLED_VERSION != "unknown" ] ; then
              break
            fi
            sleep $sleep_seconds
            while read line; do
              INSTALLED_VERSION=$line
            done < <(cat nohup.out)
            ((sleep_seconds=sleep_seconds+10))
          done
          echo "Installed Istio ... ${INSTALLED_VERSION}"
          [[ "1.8.6" == "${INSTALLED_VERSION}" ]] && installed="OK" || installed="KO"
          echo "::set-output name=installed::$installed"
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }} # automatically provided
      - uses: GoogleCloudPlatform/release-please-action@v2.7.0
        id: release
        if: ${{ !env.ACT && steps.asdf-plugin-latest-test.outputs.installed == 'OK' && steps.asdf-istio-plugin-pinned-test.outputs.installed == 'OK' }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          bump-minor-pre-major: true
