name: Build and Release Plugin

on:
  push:
    paths:
      - "bin/**"
      - "!.github/workflows/**"
      - ".github/workflows/main.yml"
jobs:
  buildAnDeploySite:
    name: "Build and Release Plugin"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: asdf_plugin_test
        run: |
          sudo apt install curl git
          git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.8.1
          . $HOME/.asdf/asdf.sh
          asdf plugin test istio . 'istioctl version --short --remote=false'
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }} # automatically provided

      - uses: GoogleCloudPlatform/release-please-action@v2.7.0
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          bump-minor-pre-major: true
